import asyncio

from app.cache import get_cached_track, init_cache_db, set_cached_track
from app.formatting import (
    build_caption,
    build_inline_description,
    build_track_payload,
    format_date_ru,
    get_meta_content,
    is_suspicious_yandex_label,
    normalize_text,
    should_show_label,
    tokenize_text,
)
from app import sources
from app.sources import (
    aiohttp,
    build_unsupported_url_message,
    build_yandex_payload,
    clean_soundcloud_title,
    clean_youtube_music_artist,
    clean_youtube_music_track,
    classify_music_url,
    extract_apple_music_song_url,
    extract_json_from_script,
    extract_track_id,
    extract_yandex_label_name,
    extract_yandex_track_ref,
    get_album_label,
    get_spotify_token,
    get_track_info,
    get_yandex_client,
    parse_apple_music,
    parse_apple_music_ld_json,
    parse_music_url,
    parse_soundcloud,
    parse_youtube,
    parse_youtube_music,
    parse_yandex_music,
    refine_yandex_payload,
    resolve_redirect_url,
    resolve_spotify_link,
    score_yandex_candidate,
    search_spotify_tracks,
)
from app.telegram_app import (
    auto_delete_messages,
    bot,
    dp,
    generate_keyboard,
    handle_music_link,
    inline_handler,
    main,
    on_startup,
    send_help,
    should_auto_delete,
)

__all__ = [
    "aiohttp",
    "auto_delete_messages",
    "bot",
    "build_caption",
    "build_inline_description",
    "build_unsupported_url_message",
    "build_track_payload",
    "build_yandex_payload",
    "clean_soundcloud_title",
    "clean_youtube_music_artist",
    "clean_youtube_music_track",
    "classify_music_url",
    "dp",
    "extract_apple_music_song_url",
    "extract_json_from_script",
    "extract_track_id",
    "extract_yandex_label_name",
    "extract_yandex_track_ref",
    "format_date_ru",
    "generate_keyboard",
    "get_album_label",
    "get_cached_track",
    "get_meta_content",
    "get_spotify_token",
    "get_track_info",
    "get_yandex_client",
    "handle_music_link",
    "inline_handler",
    "init_cache_db",
    "is_suspicious_yandex_label",
    "main",
    "normalize_text",
    "on_startup",
    "parse_apple_music",
    "parse_apple_music_ld_json",
    "parse_music_url",
    "parse_soundcloud",
    "parse_youtube",
    "parse_youtube_music",
    "parse_yandex_music",
    "refine_yandex_payload",
    "resolve_redirect_url",
    "resolve_spotify_link",
    "score_yandex_candidate",
    "search_spotify_tracks",
    "send_help",
    "set_cached_track",
    "should_auto_delete",
    "should_show_label",
    "sources",
    "tokenize_text",
]


if __name__ == "__main__":
    asyncio.run(main())
